name: Docker Build and Test

on:
  pull_request:

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t aqm-eval:latest .

    - name: Run pre-commit script with source code
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          AQM-Eval:latest \
          conda run -n aqm-eval --no-capture-output python pre-commit.py
